const FIREBASE_CONFIG={apiKey:"AIzaSyClarkGolfAcademyKey",authDomain:"iclarkgolf.firebaseapp.com",projectId:"iclarkgolf",storageBucket:"iclarkgolf.appspot.com",messagingSenderId:"123456789",appId:"1:123456789:web:abcdef"};
const DB={BLOGS:'blogs',ACCOMMODATIONS:'accommodations',GREENFEE:'greenfee',CADDIES:'caddies',QUOTES:'quotes',PACKAGES:'packages',SETTINGS:'settings'};
const ADMIN_PW='iclark2024!';
function checkAdmin(){const pw=localStorage.getItem('iclark_admin');if(pw!==ADMIN_PW){const input=prompt('관리자 비밀번호를 입력하세요:');if(input!==ADMIN_PW){alert('비밀번호가 틀렸습니다.');window.location.href='index.html';return false;}localStorage.setItem('iclark_admin',input);}return true;}
function formatDate(date){if(!date)return '';const d=date instanceof Date?date:new Date(date);return d.toLocaleDateString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit'});}
function formatDateRange(start,end){if(!start||!end)return '';const s=new Date(start),e=new Date(end);const nights=Math.round((e-s)/(1000*60*60*24));return formatDate(s)+' ~ '+formatDate(e)+' ('+nights+'박 '+(nights+1)+'일)';}
function getNights(start,end){if(!start||!end)return 0;return Math.round((new Date(end)-new Date(start))/(1000*60*60*24));}
function formatPrice(num,currency='$'){if(!num&&num!==0)return '-';return currency+Number(num).toLocaleString();}
function formatPHP(num){if(!num&&num!==0)return '-';return '₱'+Number(num).toLocaleString();}
function showToast(msg,type='success'){const colors={success:'#1D9E75',error:'#e74c3c',info:'#534AB7'};const t=document.createElement('div');t.style.cssText='position:fixed;bottom:80px;left:50%;transform:translateX(-50%);background:'+colors[type]+';color:#fff;padding:12px 24px;border-radius:100px;font-family:Nunito,sans-serif;font-size:13px;font-weight:700;z-index:9999;white-space:nowrap;';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2800);}
function showLoading(el,text='저장 중...'){if(!el)return;el._origText=el.textContent;el.textContent=text;el.disabled=true;el.style.opacity='.7';}
function hideLoading(el){if(!el)return;el.textContent=el._origText||'완료';el.disabled=false;el.style.opacity='1';}
function createQuoteData(data){return{id:Date.now().toString(),createdAt:new Date().toISOString(),status:'pending',purpose:data.purpose||'',purposeLabel:data.purposeLabel||'',accommodation:data.accommodation||'',accomLabel:data.accomLabel||'',checkIn:data.checkIn||'',checkOut:data.checkOut||'',nights:data.nights||0,golfers:data.golfers||1,nonGolfers:data.nonGolfers||0,golfCourses:data.golfCourses||[],totalUSD:data.totalUSD||0,memo:data.memo||'',contact:data.contact||''};}
const KAKAO_URL='https://pf.kakao.com/_nbHKX/chat';
function openKakao(message){window.open(message?KAKAO_URL+'?message='+encodeURIComponent(message):KAKAO_URL,'_blank');}
const QUOTE_KEY='iclark_quote_draft';
function saveQuoteDraft(data){localStorage.setItem(QUOTE_KEY,JSON.stringify(data));}
function loadQuoteDraft(){try{return JSON.parse(localStorage.getItem(QUOTE_KEY)||'null');}catch{return null;}}
function clearQuoteDraft(){localStorage.removeItem(QUOTE_KEY);}
const PURPOSES=[{value:'golf-tour',label:'골프 여행',emoji:'⛳',desc:'골프 + 관광·쇼핑·휴식',recAccom:['clarkton','mango','emmaus','oasis']},{value:'golf-rest',label:'골프 휴식',emoji:'🌴',desc:'여유로운 골프 + 리조트 휴가',recAccom:['oasis','mango','clarkton','emmaus']},{value:'training',label:'전지훈련',emoji:'🏋️',desc:'집중 훈련, 스코어 향상',recAccom:['iclark']},{value:'family',label:'가족 동반',emoji:'👨‍👩‍👧',desc:'가족과 함께하는 클락 여행',recAccom:['oasis','mango','clarkton','emmaus']},{value:'group',label:'단체 투어',emoji:'🤝',desc:'동호회·팀 단체 골프 여행',recAccom:['iclark','clarkton','oasis','mango','emmaus']}];
const ACCOMMODATIONS=[{id:'clarkton',type:'hotel',name:'클락턴 호텔',stars:3,price:'시세 적용',tag:'호텔'},{id:'mango',type:'hotel',name:'망고 스위트',stars:4,price:'시세 적용',tag:'호텔'},{id:'emmaus',type:'hotel',name:'엠마우스 콘도텔',stars:3,price:'시세 적용',tag:'호텔'},{id:'oasis',type:'hotel',name:'오아시스 호텔',stars:3,price:'시세 적용',tag:'호텔'},{id:'iclark',type:'local',name:'iClark 전용숙소',stars:0,price:'$45/일 (올인클루시브)',tag:'전지훈련 전용'}];
const GOLF_COURSES=[{id:'pradera',name:'프라데라',weekday:2500,weekend:3000},{id:'korea-cc',name:'코리아 CC',weekday:1800,weekend:2200},{id:'luisita',name:'루이시타',weekday:1600,weekend:1800},{id:'dheights',name:'디하이츠',weekday:2900,weekend:3400},{id:'mimosa',name:'미모사',weekday:3900,weekend:4400},{id:'new-asia',name:'뉴 아시아',weekday:1000,weekend:1000},{id:'beverly',name:'베벌리',weekday:1000,weekend:1000},{id:'royal',name:'로얄 센트럴',weekday:1500,weekend:2000},{id:'lakewood',name:'레이크우드',weekday:800,weekend:800},{id:'vista-am',name:'비스타 오전',weekday:3600,weekend:4000},{id:'vista-pm',name:'비스타 오후',weekday:3200,weekend:3600},{id:'hann',name:'한 리저브',weekday:8600,weekend:8600},{id:'subic',name:'수빅 인터내셔널',weekday:6000,weekend:10000},{id:'puning',name:'푸닝',weekday:4800,weekend:4800}];
const CADDY_FEE=600,CART_FEE=1500,CONSUM_FEE=300,INS_FEE=150,PHP_TO_USD=0.018;
function phpToUsd(php){return Math.round(php*PHP_TO_USD*100)/100;}